import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQuery from "@/components/ReactQuery";
import { Session } from "next-auth";
import { ReactNode } from "react";
import NextAuthProvider from "@/components/NextAuthProvider";
import { ChakraProvider } from "@chakra-ui/react";

interface NextAuthProps {
  children: ReactNode;
  session: Session | null | undefined;
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "spoversity",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }: NextAuthProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider session={session}>
          <ReactQuery>{children}</ReactQuery>
        </NextAuthProvider>
      </body>
    </html>
  );
}
